print("Let's test your BOOLEAN CHOPS!")

print("True and True")
input("?-->")
print("Answer: ",True and True)
print("False and True")
input("?-->")
print("Answer: ",False and True)
print("1 == 1 and 2 == 1")
input("?-->")
print("Answer: ",1 == 1 and 2 == 1)
print('"test" == "test"')
input("?-->")
print("Answer: ","test" == "test")
print("1 == 1 and 2 != 1")
input("?-->")
print("Answer: ",1 == 1 and 2 != 1)
print("True and 1 == 1")
input("?-->")
print("Answer: ",True and 1 == 1)
print("False and 0 != 0")
input("?-->")
print("Answer: ",False and 0 != 0)
print("True or 1 == 1")
input("?-->")
print("Answer: ",True or 1 == 1)
print(''"test != testing"')
input("?-->")
print("Answer: ","test" != "testing")
print("1 != 0 and 2 == 1")
input("?-->")
print("Answer: ",1 != 0 and 2 == 1)
print("'test' == 1")
input("?-->")
print("Answer: ","test" == 1)
print("not(True and False)")
input("?-->")
print("Answer: ",not(True and False))
print("not(1 == 1 and 0 != 1)")
input("?-->")
print("Answer: ",not(1 == 1 and 0 != 1))
print("not(10 == 1 or 1000 == 1000)")
input("?-->")
print("Answer: ",not(10 == 1 or 1000 == 1000))
print("not(1 != 10 or 3 == 4)")
input("?-->")
print("Answer: ",not(1 != 10 or 3 == 4))
print('not("testing" == "testing" and "Zed" == "Cool Guy")')
input("?-->")
print("Answer: ",not("testing" == "testing" and "Zed" == "Cool Guy"))
print('1 == 1  and (not("testing" == 1 or 1 == 0))')
input("?-->")
print("Answer: ",1 == 1  and (not("testing" == 1 or 1 == 0)))

print('"chunky" == "bacon" and (not (3 == 4 or 3 ==3)') 
input("?-->")
print("Answer: ",("chunky" == "bacon") and (not (3 == 4 or 3 ==3))
print('3 == 3  and (not("testing" == 1 or "Python" == "Fun"))')
input("?-->")
print("Answer: ",3 == 3 and (not ("testing" == "testing" or "Python == "Fun")))